<template>
    <div class="category_part">
        <div id="a-page">
            <div id="nav-belt">
                <div id="nav-shop">
                    <a class="nav-a nav-a-2" data-ux-jq-mouseenter="true" id="nav-link-shopall" tabindex="15">
                        <span class="nav-line-1"></span>
                        <span class="nav-line-2">Category<span class="nav-icon nav-arrow" style="visibility: visible;"></span>
                        </span>
                    </a>
                </div>
                <!-- Vertical menu start here -->
                <div id="pageContent" class="a-section a-spacing-none" role="main">
                    <!-- Vertical menu End Here-->
                </div>

                <div id="nav-flyout-anchor">
                    <div id="nav-flyout-prime" class="nav-coreFlyout nav-flyout">
                        <div class="nav-arrow">
                            <div class="nav-arrow-inner"></div>
                        </div>
                        <div class="nav-template nav-flyout-content nav-spinner"></div>
                    </div>
                    <div id="nav-flyout-cart" class="nav-cartFlyout nav-flyout">
                        <div class="nav-arrow">
                            <div class="nav-arrow-inner"></div>
                        </div>
                        <div class="nav-template nav-flyout-content nav-spinner"></div>
                    </div>
                    <div id="nav-flyout-wishlist" class="nav-coreFlyout nav-flyout">
                        <div class="nav-arrow">
                            <div class="nav-arrow-inner"></div>
                        </div>
                        <div class="nav-template nav-flyout-content nav-spinner"></div>
                    </div>
                    <div id="nav-flyout-shopAll" class="nav-catFlyout nav-flyout" style="display: none; position: absolute; top: 52px; left: 15px;">
                        <div class="nav-arrow" style="position: absolute; left: 100.703px;">
                            <div class="nav-arrow-inner"></div>
                        </div>
                        <div class="nav-template nav-flyout-content nav-tpl-itemList"> <span class="nav-hasPanel                              nav-item" data-nav-panelkey="hardwarePanel" role="navigation" aria-label="Computer Hardware"> <span class="nav-text">Computer Hardware</span> </span> <span class="nav-hasPanel                              nav-item" data-nav-panelkey="circuitsPanel" role="navigation" aria-label="Integrated Circuits"> <span class="nav-text">Integrated Circuits</span> </span> <span class="nav-hasPanel                              nav-item" data-nav-panelkey="transisPanel" role="navigation" aria-label="Transistors"> <span class="nav-text">Transistors</span> </span> <span class="nav-hasPanel                              nav-item" data-nav-panelkey="PrimeVideoPanel" role="navigation" aria-label="Power Banks"> <span class="nav-text">Power Banks</span> </span> <span class="nav-hasPanel                              nav-item" data-nav-panelkey="PrimeMusicPanel" role="navigation" aria-label="Mobile Phones"> <span class="nav-text">Mobile Phones</span> </span>
                            <div class="nav-divider"></div> <span class="nav-hasPanel                              nav-item" data-nav-panelkey="PhonesAccessoriesPanel" role="navigation" aria-label="Chargers"> <span class="nav-text">Chargers</span> </span> <span class="nav-hasPanel                              nav-item" data-nav-panelkey="TvApplElecPanel" role="navigation" aria-label="Hard Drives"> <span class="nav-text">Hard Drives</span> </span> <span class="nav-hasPanel                              nav-item" data-nav-panelkey="MensFashionPanel" role="navigation" aria-label="Generators"> <span class="nav-text">Generators</span> </span> <span class="nav-hasPanel                              nav-item" data-nav-panelkey="WomensFashionPanel" role="navigation" aria-label="Motors"> <span class="nav-text">Motors</span> </span> <span class="                    nav-hasPanel                              nav-item" data-nav-panelkey="HomeKitchenPanel" role="navigation" aria-label="Hand Tools"> <span class="nav-text">Hand Tools</span> </span> <span class="                    nav-hasPanel                              nav-item" data-nav-panelkey="BeautyHpcPanel" role="navigation" aria-label="Air Conditioners"> <span class="nav-text">Air Conditioners</span> </span> <span class="                    nav-hasPanel                              nav-item" data-nav-panelkey="SportsOutdoorsPanel" role="navigation" aria-label="Sports, Fitness, Bags, Luggage"> <span class="nav-text">Sports, Fitness, Bags, Luggage</span> </span> <span class="                    nav-hasPanel                              nav-item" data-nav-panelkey="ToysBabyPanel" role="navigation" aria-label="Toys, Baby Products, Kids" fashion'=""> <span class="nav-text">Toys, Baby Products, Kids' Fashion</span> </span> <span class="                    nav-hasPanel                              nav-item" data-nav-panelkey="AutomotivePanel" role="navigation" aria-label="Car, Motorbike, Industrial"> <span class="nav-text">Car, Motorbike, Industrial</span> </span> <span class="                    nav-hasPanel                              nav-item" data-nav-panelkey="BooksPanel" role="navigation" aria-label="Books &amp; Audible"> <span class="nav-text">Books &amp; Audible</span> <span class="nav-subtext">Just launched: Audible</span> </span> <span class="                    nav-hasPanel                              nav-item" data-nav-panelkey="MusicMoviesGamesPanel" role="navigation" aria-label="Movies, Music &amp; Video Games"> <span class="nav-text">Movies, Music &amp; Video Games</span> </span> <span class="                    nav-hasPanel                              nav-item" data-nav-panelkey="airconditionersPanel" role="navigation" aria-label="Air Conditioners"> <span class="nav-text">Air Conditioners</span> </span> <a href="/flights?_encoding=UTF8&amp;ref_=nav_shopall_sbc_desktop_flights" class="nav-link                                    nav-item"> <span class="nav-text">Flight Tickets</span> </a>
                            <div class="nav-divider"></div> <a href="/gp/site-directory?ie=UTF8&amp;ref_=nav_shopall_sbc_fullstore" class="nav-link                                nav-carat                  nav-item"> <i class="nav-icon"></i> <span class="nav-text">Full Store Directory</span> </a>
                        </div>
                        <div class="nav-subcats" style="height: auto; overflow: hidden; display: none; width: auto;">
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2 nav-colcount-3" style="display: none;"><img src="assest/Flyout_500x450._CB463264986_.png" usemap="#nav_imgmap_nav-sa-Echo" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 500px; height: 450px;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="                          nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="                          nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2 nav-colcount-3" style="display: none;"><img src="assest/RGC24_JupiterW1GC_500x500_Nov._CB479161047_.png" usemap="#nav_imgmap_nav-sa-gift-cards" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="                          nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="                          nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2 nav-colcount-3" style="display: none;"><img src="assest/Jaegerstreetflyout._CB467541377_.png" usemap="#nav_imgmap_nav-sa-kindle" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                    <div class="nav-divider"></div>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Free Kindle Reading Apps</span> </a> <a href="#" class="nav-link                                    nav-item" target="_blank"> <span class="nav-text">Kindle Cloud Reader</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Manage Your Content and Devices</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle eBooks</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Prime Reading</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Unlimited</span> <span class="nav-subtext">With a free 30-day trial</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Deals on Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Exam Central</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle eTextbooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBook Bestsellers</span> </a>
                                        <div class="nav-divider"></div> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBooks in Indian Languages</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Hindi</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Tamil</span> </a>
                                    </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2 nav-colcount-3" style="display: none;"><img src="assest/RGC24_JupiterW1GC_500x500_Nov._CB479161047_.png" usemap="#nav_imgmap_nav-sa-gift-cards" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2 nav-colcount-3" style="display: none;"><img src="assest/Jaegerstreetflyout._CB467541377_.png" usemap="#nav_imgmap_nav-sa-kindle" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                    <div class="nav-divider"></div>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Free Kindle Reading Apps</span> </a> <a href="#" class="nav-link                                    nav-item" target="_blank"> <span class="nav-text">Kindle Cloud Reader</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Manage Your Content and Devices</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle eBooks</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Prime Reading</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Unlimited</span> <span class="nav-subtext">With a free 30-day trial</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Deals on Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Exam Central</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle eTextbooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBook Bestsellers</span> </a>
                                        <div class="nav-divider"></div> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBooks in Indian Languages</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Hindi</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Tamil</span> </a>
                                    </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2 nav-colcount-3" style="display: none;"><img src="assest/RGC24_JupiterW1GC_500x500_Nov._CB479161047_.png" usemap="#nav_imgmap_nav-sa-gift-cards" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2 nav-colcount-3" style="display: none;"><img src="assest/Jaegerstreetflyout._CB467541377_.png" usemap="#nav_imgmap_nav-sa-kindle" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                    <div class="nav-divider"></div>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Free Kindle Reading Apps</span> </a> <a href="#" class="nav-link                                    nav-item" target="_blank"> <span class="nav-text">Kindle Cloud Reader</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Manage Your Content and Devices</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="                          nav-title                        nav-item"> <span class="nav-text">Kindle eBooks</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Prime Reading</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Unlimited</span> <span class="nav-subtext">With a free 30-day trial</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Deals on Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Exam Central</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle eTextbooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBook Bestsellers</span> </a>
                                        <div class="nav-divider"></div> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBooks in Indian Languages</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Hindi</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Tamil</span> </a>
                                    </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2 nav-colcount-3" style="display: none;"><img src="assest/men._CB468888570_.jpg" alt="mens fashion" usemap="#nav_imgmap_nav-sa-mens-fashion" hidefocus="true" class="nav-promo" style="bottom: -14px; right: -1px; width: 500px; height: 450px;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2 nav-colcount-3" style="display: none;"><img src="assest/Women-fashion_Flyout_500x450._CB468888565_.jpg" usemap="#nav_imgmap_nav-sa-womens-fashion" hidefocus="true" class="nav-promo" style="bottom: -14px; right: -1px; width: 500px; height: 450px;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                    <div class="nav-divider"></div>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Free Kindle Reading Apps</span> </a> <a href="#" class="nav-link                                    nav-item" target="_blank"> <span class="nav-text">Kindle Cloud Reader</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Manage Your Content and Devices</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle eBooks</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Prime Reading</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Unlimited</span> <span class="nav-subtext">With a free 30-day trial</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Deals on Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Exam Central</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle eTextbooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBook Bestsellers</span> </a>
                                        <div class="nav-divider"></div> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBooks in Indian Languages</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Hindi</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Tamil</span> </a>
                                    </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2"><img src="assest/GW_Flyout_500x450_Flyout._CB487102089_.png" usemap="#nav_imgmap_nav-sa-home-kitchen" hidefocus="true" class="nav-promo" style="bottom: -15px; right: 0px; width: 100%; height: 450px;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                    <div class="nav-divider"></div>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Free Kindle Reading Apps</span> </a> <a href="#" class="nav-link                                    nav-item" target="_blank"> <span class="nav-text">Kindle Cloud Reader</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Manage Your Content and Devices</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle eBooks</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Prime Reading</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Unlimited</span> <span class="nav-subtext">With a free 30-day trial</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Deals on Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Exam Central</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle eTextbooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBook Bestsellers</span> </a>
                                        <div class="nav-divider"></div> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBooks in Indian Languages</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Hindi</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Tamil</span> </a>
                                    </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2"><img src="assest/RGC24_JupiterW1GC_500x500_Nov._CB479161047_.png" usemap="#nav_imgmap_nav-sa-gift-cards" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2"><img src="assest/Jaegerstreetflyout._CB467541377_.png" usemap="#nav_imgmap_nav-sa-kindle" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                    <div class="nav-divider"></div>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Free Kindle Reading Apps</span> </a> <a href="#" class="nav-link                                    nav-item" target="_blank"> <span class="nav-text">Kindle Cloud Reader</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Manage Your Content and Devices</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle eBooks</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Prime Reading</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Unlimited</span> <span class="nav-subtext">With a free 30-day trial</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Deals on Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Exam Central</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle eTextbooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBook Bestsellers</span> </a>
                                        <div class="nav-divider"></div> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBooks in Indian Languages</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Hindi</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Tamil</span> </a>
                                    </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2"><img src="assest/RGC24_JupiterW1GC_500x500_Nov._CB479161047_.png" usemap="#nav_imgmap_nav-sa-gift-cards" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="                          nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="                          nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2"><img src="assest/xcm_manual-1173179_in_books_fathers_day_500x450_1559145443._CB463276719_.png" alt="Father's day bookstore" usemap="#nav_imgmap_nav-sa-books" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 500px; height: 450px;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                    <div class="nav-divider"></div>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Free Kindle Reading Apps</span> </a> <a href="#" class="nav-link                                    nav-item" target="_blank"> <span class="nav-text">Kindle Cloud Reader</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Manage Your Content and Devices</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle eBooks</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Prime Reading</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Unlimited</span> <span class="nav-subtext">With a free 30-day trial</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Deals on Kindle eBooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Exam Central</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle eTextbooks</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBook Bestsellers</span> </a>
                                        <div class="nav-divider"></div> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">eBooks in Indian Languages</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Hindi</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Tamil</span> </a>
                                    </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Kindle E-readers</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">All-new Kindle Paperwhite</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Paperwhite Starter Pack</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle Oasis</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Certified Refurbished</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Kindle E-Reader Accessories</span> <span class="nav-subtext">Covers, chargers, sleeves and more</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">See all Kindle E-readers</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                            <div class="nav-template nav-subcat nav-tpl-itemList nav-colcount-2"><img src="assest/RGC24_JupiterW1GC_500x500_Nov._CB479161047_.png" usemap="#nav_imgmap_nav-sa-gift-cards" hidefocus="true" class="nav-promo" style="bottom: -14px; right: 0px; width: 100%; height: auto;">
                                <div class="nav-column nav-column-first"> <span class="nav-title                        nav-item"> <span class="nav-text">Gift Cards</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text"> All Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Gift Boxes, Gift Tags, Greeting Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Popular Brand Gift Vouchers </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Birthday Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Wedding &amp; Anniversary </span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Best Wishes &amp; Thank You</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Corporate Gift Cards</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Add a gift card</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                                <div class="nav-column nav-column-notfirst nav-column-break"> <span class="nav-title                        nav-item"> <span class="nav-text">Recharges</span> </span>
                                    <div class="nav-panel"> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">Mobile Recharges</span> </a> <a href="#" class="nav-link                                    nav-item"> <span class="nav-text">computer Recharges</span> </a> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="nav-flyout-yourAccount" class="nav-coreFlyout nav-flyout">
                        <div class="nav-arrow">
                            <div class="nav-arrow-inner"></div>
                        </div>
                        <div class="nav-template nav-flyout-content nav-spinner"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</template>

<script>
export default {
    
}
</script>